version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_db_container
    restart: always
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/XI0YnciAGlBx
    volumes:
      - conf:/var/lib/neo4j/conf
      - data:/var/lib/neo4j/data
      - import:/var/lib/neo4j/import
      - logs:/var/lib/neo4j/logs
      - plugins:/var/lib/neo4j/plugins
volumes:
    conf:
    data:
    import:
    logs:
    plugins:
